services:
  storage:
    image: redis
    volumes:
      - /media/sf_2.5/redis/data:/data
    # ports:
    #   - 6379:6379
  counter:
    image: node:19.8
    working_dir: /app
    volumes:
      - /media/sf_2.5/counter:/app
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    ports:
      - 3001:3001
    command: npm run dev
    depends_on:
      - storage
  api:
    image: node:19.8
    working_dir: /app
    volumes:
      - /media/sf_2.5/api:/app
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3001
    ports:
      - 80:3000
    command: npm run dev
