services:
  storage:
    image: redis
  counter:
    build: ./counter
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    ports:
      - 3001:3001
    depends_on:
      - storage
  api:
    build: ./api
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3001
    ports:
      - 80:3000
